### ISSUE TITLE
Add chart-releaser-example (or demo) repo and update README

### ISSUE THREAD

**Issue by scottrigby** [helm/chart-releaser#10]
This should be automated.

**Comment by sgandon** [comment]
that would be great indeed to have a gihub example that was setup with this tools.

**Comment by unguiculus** [comment]
@sgandon Have a look here: https://github.com/unguiculus/gh-pages-helm-chart-repo-example

Hopefully soon, we're going to provide a set of GitHub actions that can be used.

**Comment by sgandon** [comment]
@unguiculus thanks for this.

**Comment by scottrigby** [comment]
Cross linking the demo for actions: https://github.com/helm/charts-repo-actions-demo

**Comment by scottrigby** [comment]
Closing - this was done earlier in the year ✅
