### ISSUE TITLE
404 when trying to use private repository

### ISSUE THREAD

**Issue by lukaszmitka-aptiv** [helm/chart-releaser#100]
I'm trying to use chart-releaser in a private repository.
Steps:
- create private repository
- enable gh-pages (public)
- `cr package ...`
- `cr upload ...`
- `cr index --push ...`
- `helm repo add my_private_repo <owner>.github.io/<repo_name> --username <user> --password <token>`
- `helm pull my_private_repo/<chart>` <-ERROR
Error: failed to fetch `https://github.com/<owner>/<repo>/releases/download/<release>/<chart>.tgz`: 404 Not Found

Am I missing something or chart-releaser is useless on private repositories?

**Comment by lukaszmitka-aptiv** [comment]
Appears to be issue of helm itself https://github.com/helm/helm/issues/7451

**Comment by ItaiHuber** [comment]
did you resolve the issue?

**Comment by lukasz-mitka** [comment]
> did you resolve the issue?

No, see my comment
>Appears to be issue of helm itself https://github.com/helm/helm/issues/7451

However solution I'm considering is switching over to OCI registries https://helm.sh/docs/topics/registries/ and using ghcr.io
