### ISSUE TITLE
Timeline for 1.2.1 release

### ISSUE THREAD

**Issue by afritzler** [helm/chart-releaser#117]
Any plans when the next version will be released? Waiting here for https://github.com/helm/chart-releaser/pull/110 :)

**Comment by cpanato** [comment]
will do this week

**Comment by jalavosus** [comment]
@cpanato any updates on this? We're hoping to integrate #111 into our private helm charts workflow

**Comment by Ornias1993** [comment]
Same here, this is quite relevant for a lot of repositories.
