### ISSUE TITLE
Feature: Changelog

### ISSUE THREAD

**Issue by estahn** [helm/chart-releaser#118]
We had multiple users ask for a changelog on the GitHub release. We use semantic-release but not sure how to wire this up.

**Comment by smlx** [comment]
related: https://github.com/helm/chart-releaser-action/issues/44

not sure if this feature request belongs in the action or in `cr` itself.

**Comment by pratikbalar** [comment]
I have bash based chart release pipeline in our CI, and I'm handling changelog with [git-chglog](https://github.com/git-chglog/git-chglog) cli, here's loosely version of it

```bash 
## tagging new chart version
git tag ${CHART_NAME}-${NEW_VERSION} ${COMMIT_SHA} 

## Generate changelog with git-chglog
git-chglog \
  -o ${CHART_NAME}-${NEW_VERSION}.md \
  --path charts/${CHART_NAME} \
  ${CHART_NAME}-${OLD_VERSION}..${CHART_NAME}-${NEW_VERSION}

## delete tag if needed
git tag -d ${CHART_NAME}-${NEW_VERSION}

``` 

if I interpret it O/P
```bash
## tagging new chart version
git tag prometheus-0.0.1 11111111111111111111111111111111

## Generate changelog with git-chglog
git-chglog \
  -o prometheus-0.0.1.md \
  --path charts/prometheus \
  prometheus-0.0.0..prometheus-0.0.1
  
## delete tag if needed  
git tag -d prometheus-0.0.1 11111111111111111111111111111111

```

**Comment by pratikbalar** [comment]
### OR
#### You can give option to add body in release i.e. `cr upload --release-body <file or text>`, so we can add our custom one.

**Comment by thesuperzapper** [comment]
@unguiculus are you ok with a feature like `cr upload --release-body <file_path>`?

This will make it possible for users to store things like changelogs in the GitHub release text.

**Comment by pratikbalar** [comment]
@thesuperzapper  But then how can it can distinguish for which chart release will set body cause AFAIK it will check charts in `CR_PACKAGE_PATH` and based on that it will release multiple if there

**Comment by estahn** [comment]
Atlassian came up with an interesting approach, which they called changesets (https://github.com/atlassian/changesets). I've seen this being used in [Backstage](https://github.com/backstage/backstage). This could solve the above issue as it will also allow recording migration strategies, e.g. structure changes in `values.yaml`.

**Comment by thesuperzapper** [comment]
Regardless, we still need to support some way of specifying the body of the release in `chart-releaser`.

I think the proposed `cr upload --release-body <file_path>` is a good idea.

**Comment by estahn** [comment]
@thesuperzapper I think you skipped @pratikbalar comment.

> But then how can it can distinguish for which chart release will set body cause AFAIK it will check charts in `CR_PACKAGE_PATH` and based on that it will release multiple if there

**Comment by pratikbalar** [comment]
> Atlassian came up with an interesting approach, which they called changesets (https://github.com/atlassian/changesets). I've seen this being used in [Backstage](https://github.com/backstage/backstage). This could solve the above issue as it will also allow recording migration strategies, e.g. structure changes in `values.yaml`.

Kindly tell us more about it if you can

**Comment by macobo** [comment]
I think we can standardize this beyond `--release-body` by copying e.g. dependabot for a default.

E.g.

> CHART DESCRIPTION
>
> Updates chart to version X
>
> Commits:
> Collapsible section with list of all commits since master

**Comment by aabouzaid** [comment]
This feature is really important to automate the whole workflow.

To set the release notes after the actual release I need to do a lot of kung-fu! (which is error-prone) I need to extract the updated charts and call GH API twice because even GH CLI [doesn't support update release](https://github.com/cli/cli/issues/1997) at the moment!

For that reason, I've created this PR no. #137 to add chart release-notes or changelog (without any coupling to an external source).

**Comment by aabouzaid** [comment]
@cpanato since the PR no. #137 is merged, the last thing to close this issue is to release a new version.
Is there an expected date/schedule for the release?

**Comment by LeoColomb** [comment]
> In theory, these could be parsed, prettified and set similarly to how the current implementation uses the Chart.yaml's description as the release description: [`main`/pkg/releaser/releaser.go#L322](https://github.com/helm/chart-releaser/blob/main/pkg/releaser/releaser.go#L322) However, this would couple the chart-releaser implementation to ArtifactHub's annotations which may not be desirable.

Indeed, but like the file for the release notes, I guess the annotation to use can be managed by the configuration?

**Comment by cpanato** [comment]
@aabouzaid @LeoColomb are you willing to submit a PR to contribute to some docs in how to use that?

the release will come soon, need to perform some tests

will close this issue since it is already merged to the main branch

**Comment by chgl** [comment]
> > In theory, these could be parsed, prettified and set similarly to how the current implementation uses the Chart.yaml's description as the release description: [`main`/pkg/releaser/releaser.go#L322](https://github.com/helm/chart-releaser/blob/main/pkg/releaser/releaser.go#L322) However, this would couple the chart-releaser implementation to ArtifactHub's annotations which may not be desirable.
> 
> Indeed, but like the file for the release notes, I guess the annotation to use can be managed by the configuration?

I think the current implementation is perfect to also handle generating a changelog file from the annotations. I'm currently playing around with something like this:

```sh
cat "Chart.yaml" |
        yq e '.annotations["artifacthub.io/changes"]' - |                                                           # extract the changes annotation, which is a YAML array
        yq -o json e '.' - |                                                                                        # convert the YAML array to a JSON array
        jq 'group_by(.kind) | to_entries | map({key: .value[0].kind, value: .value})' - |                           # group the JSON array by their 'kind' - ie. the type of change
        gomplate -d chart="Chart.yaml" -d changes=stdin:///in.json -f CHANGELOG.md.gotmpl >"CHANGELOG.md" # use the JSON above as input to render the changelog
```
CHANGELOG.md.gotmpl:
```gotmpl
{{ $chart := (ds "chart") -}}
{{ $changes := (ds "changes") -}}
# Changelog

## {{ $chart.version }}

{{- range $kind := $changes }}

### {{ $kind.key | strings.Title }}

{{- range $change := $kind.value }}
- {{ $change.description }}
{{- end }}

{{- end }}
```

So the changelog.md is generated from the manually curated artifacthub annotations.

**Comment by nlamirault** [comment]
does anyone have an example of how to make a chart release with a changelog using this Github Action ?

**Comment by aabouzaid** [comment]
@nlamirault Here it is.
https://github.com/camunda-community-hub/camunda-helm/blob/bc501f7/.github/workflows/release.yaml
