### ISSUE TITLE
How to run `cr` using docker?

### ISSUE THREAD

**Issue by jtomaszewski** [helm/chart-releaser#126]
Somehow my args aren't passed to `cr` when I try to run it using `docker run -it quay.io/helmpack/chart-releaser ...` .

Any idea what's wrong? Perhaps we should add a more explicit example to README if running this using docker is non obvious.

![image](https://user-images.githubusercontent.com/1862580/123580333-f8d00b80-d81c-11eb-93ff-bc070b74d8f4.png)

Only after explicitly adding `--entrypoint /usr/local/bin/cr` option, the cr picks up args. Am I using docker incorrectly; or is sth wrong with the docker image?

![image](https://user-images.githubusercontent.com/1862580/123580531-61b78380-d81d-11eb-8aa8-42235dd64a8d.png)

**Comment by cpanato** [comment]
thanks for this issue, made a PR to fix it

just one quick note in the commands you ran, you should run `upload --help` and not `help upload`

**Comment by jtomaszewski** [comment]
Thanks. That PR will probably fix it.
