### ISSUE TITLE
Increment chart version each push

### ISSUE THREAD

**Issue by cabrinha** [helm/chart-releaser#130]
Hello, I'm looking for a tool that will automatically increment helm chart versions with each push.

Example: Chart version of "app" is currently 1.2.3 -- I open a PR and push a commit. CI takes over and packages the chart, updating the chart version to 1.2.4, the uploads it to my helm repo.

Does anything like this currently exist in an open-source project?

With the current state of chart-releaser, is the user expected to manually edit the version in `Chart.yaml` on each iteration?

**Comment by tylerauerbeck** [comment]
I don't think there's a way of doing this. But +1, would be great to see this included (as I notoriously forget to bump this). This could even be optional by just introducing this functionality through something like a `--increment` flag?

**Comment by smlx** [comment]
I think this is a bit outside the scope of `chart-releaser`. How would it know to bump major, minor, or patch version?

Tools like [ccv](https://github.com/smlx/ccv) can calculate version bumps based on commit message conventions, but it doesn't quite work for helm charts yet. Create an issue over there if you do think that support would be useful.

**Comment by cabrinha** [comment]
> I think this is a bit outside the scope of `chart-releaser`. How would it know to bump major, minor, or patch version?

I'd be happy with it only incrementing the patch version for starters. But, I think a simple solution would be a flag:

```
--increment < minor, major, default: patch >
```

**Comment by pratikbalar** [comment]
Right now I'm handing chart bumping with bash based on commit message and i so miss this feature 🙂

**Comment by cabrinha** [comment]
> Right now I'm handing chart bumping with bash based on commit message and i so miss this feature 🙂

Imagine how many others are manually bumping their chart versions or writing little bash scripts to do this simple thing.

It's a part of releasing a chart, bumping the version, so I thought I'd as the `chart-releaser` crowd to do the needful 😅

**Comment by smlx** [comment]
> Right now I'm handing chart bumping with bash based on commit message and i so miss this feature :slightly_smiling_face:

What logic are you using for the commit message parsing?

> It's a part of releasing a chart, bumping the version, so I thought I'd ask the `chart-releaser` crowd to do the needful :sweat_smile:

Ok, but helm charts are _strictly_ Semantic Versioned, which means you can't just bump the patch version every time. It is important that the version bump reflects the change, otherwise you risk shipping a breaking change in a patch release.

The only ways I know how to do that is either use a commit convention and parse the commit messages, or manually bump the version based on the content of the PR.

**Comment by cabrinha** [comment]
By virtue of looking into https://github.com/smlx/ccv, I found: https://github.com/caarlos0/svu

I'll just go with this project.
