### ISSUE TITLE
Arm Images

### ISSUE THREAD

**Issue by tylerauerbeck** [helm/chart-releaser#131]
It would be useful to publish ARM based images for those running on those arch.

An example of this can be seen in this PR for chart-testing using the `goreleaser` workflow (which appears to be similar to how it is done in this repo): https://github.com/helm/chart-testing/pull/351

Just wanted to check to see if this would be of interest before opening a PR here.

**Comment by mathew-fleisch** [comment]
I think I've done that with this PR but the change will not be seen until the next release:
https://github.com/helm/chart-releaser/pull/139

**Comment by cpanato** [comment]
it is available in this release https://github.com/helm/chart-releaser/releases/tag/v1.3.0
