### ISSUE TITLE
Build binaries for Darwin + ARM64 (M1 chip)

### ISSUE THREAD

**Issue by mkjpryor** [helm/chart-releaser#134]
Currently, there is no binary release for Darwin + ARM64, which is required for Macs with M1 chips.

The homebrew formula also does not work.

**Comment by mathew-fleisch** [comment]
I think I fixed this issue with this PR, though the change will not be seen until the next release
https://github.com/helm/chart-releaser/pull/139

**Comment by mathew-fleisch** [comment]
@cpanato What are the chances we could get you to backfill the arm64 release binaries after this change goes through 😏

**Comment by mathew-fleisch** [comment]
I am motivated to see this change through so the [asdf plugin](https://github.com/Antiarchitect/asdf-helm-cr/) for this project [works for both amd64 and arm64 based system architectures](https://github.com/Antiarchitect/asdf-helm-cr/pull/4). Backfilling the previous releases with the arm64 binaries will ensure this tool works for all versions and all systems.

**Comment by cpanato** [comment]
it is available in this release https://github.com/helm/chart-releaser/releases/tag/v1.3.0
