### ISSUE TITLE
Document how to handle dependencies

### ISSUE THREAD

**Issue by sbrunner** [helm/chart-releaser#135]
By example:

`Chart.yaml`:
```yaml
apiVersion: v2
appVersion: '1.0'
name: geoportal
version: 0.1.0
dependencies:
  - name: common
    repository: https://camptocamp.github.io/helm-common
    version: 0.1.1
```

`helm dependency update` =>
```
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://camptocamp.github.io/helm-common" chart repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading common from repo https://camptocamp.github.io/helm-common
Deleting outdated charts
```

`cr package .` =>
```
Error: no repository definition for https://camptocamp.github.io/helm-common
Usage:
  cr package [CHART_PATH] [...] [flags]

Flags:
  -h, --help                     help for package
      --key string               Name of the key to use when signing
      --keyring string           Location of a public keyring (default "/home/sbrunner/.gnupg/pubring.gpg")
  -p, --package-path string      Path to directory with chart packages (default ".cr-release-packages")
      --passphrase-file string   Location of a file which contains the passphrase for the signing key. Use '-' in order to read from stdin
      --sign                     Use a PGP private key to sign this package

Global Flags:
      --config string   Config file (default is $HOME/.cr.yaml)
```

`cr version` =>
```
Version:         v1.2.1
Git commit:      6fd1ce2df89d0420b458d182287d72614e551f60
Date:            2021-05-10T12:34:50Z
License:         Apache 2.0
```

`helm version` =>
```
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Did I something wrong?

**Comment by sbrunner** [comment]
Notes that:
- I do a test with a dependency that comes from bitnami, and it's working
- I publish the common also with `cr` from here: https://github.com/camptocamp/helm-common/blob/master/Chart.yaml

Does anyone have an idea?

**Comment by sbrunner** [comment]
I just find the workarond(?)
I should run:
`helm repo add common https://camptocamp.github.io/helm-common`
before the `cr` commands
Shouldn't be automatically done?

**Comment by stevehipwell** [comment]
@sbrunner I use `helm repo add` as I can't find a "supported" way of doing this like the [chart-repos config](https://github.com/helm/chart-testing#using-private-chart-repositories) for _chart-testing_.

**Comment by sbrunner** [comment]
Effectively, it can be like that :-)

**Comment by AntonOfTheWoods** [comment]
Is it just me or should this at the very least be documented in the `README`? It just seems a bit ridiculous to not either (better) do it automatically, or at least document it...

**Comment by cpanato** [comment]
@AntonOfTheWoods, are you willing to open the PR to update the doc to reflect that?

**Comment by AntonOfTheWoods** [comment]
@cpanato , unfortunately there weren't enough docs for my small brain to be able to do anything useful. Because I just kept getting incomprehensible error messages I abandoned trying to use it.

If the project had a minimum walk-through for getting something up on github pages, I would have been more than happy to contribute. This looks very much like any internal project that isn't intended for wider consumption though. I found a couple of walk-throughs from a couple of years ago that didn't work either - partly because of this issue but there were also others. Writing docs is extremely annoying... but it should really be done by people who actually know how things are supposed to work, and that's not me.

**Comment by cpanato** [comment]
Okay, that's okay, but don't expect that to happen soon. I have other priorities for now, and we are struggling to help with the project. I am trying my best to keep this up.

I will try to find some time to review this issue in depth and see what I can do, but it will be very helpful if others want to tackle this.
cc @davidkarlsen
