### ISSUE TITLE
Not producing index.yaml, please help debug (tried everything I could think of)

### ISSUE THREAD

**Issue by mysticaltech** [helm/chart-releaser#138]
Hello folks,

First of all thanks for your good work! I am trying to produce an **index.yaml** for the charts over at https://github.com/arangodb/kube-arangodb/tree/master/chart, but there is no **index.yaml** being created. 

The following command 

```
cr index --charts-repo https://github.com/arangodb/kube-arangodb/tree/master/chart --owner arangodb --git-repo kube-arangodb --index-path ./index.yaml
```

Returns this
```
UpdateIndexFile new index at ./index.yaml
Index ./index.yaml did not change
```

With no **index.yaml** anywhere to be found! I'm on Linux Fedora 33. Any ideas why that is happening?

**Comment by politician** [comment]
@cpanato I cannot work out how to create an index.yaml with `cr index` for my own chart repo

Any pointer on the right command to achieve what OP was looking to achieve?

**Comment by politician** [comment]
I have solved my problem which was in understanding how this tool is meant to be used. I think @mysticaltech was in the same situation.

`cr index` is meant to be used after `cr package` so it expects at least one packaged chart (.tgz) in the path set by `--package-path` **as well as** having it uploaded to a GH release.
Then it will generate a new/updated `index.yaml` for these charts only. If the existing `index.yaml` contains other charts they will not be touched and only those local charts will be updated/added.

So to answer @mysticaltech original question, he would have to:

1. Clone the repo `git clone git@github.com:arangodb/kube-arangodb.git`
2. Download the latest packages from the GH releases (or package them from the code) to `./packages`
3. `cr index -o arangodb -r kube-arangodb --release-name-template "{{ .Version }}" -p ./packages -i .`

**Comment by mysticaltech** [comment]
Thanks, you @politician, for the nice explanation, really appreciated it!
