### ISSUE TITLE
Support GitHub Pages Index Path other than repository root

### ISSUE THREAD

**Issue by caleblloyd** [helm/chart-releaser#150]
The `index.yaml` on the GitHub Pages branch is currently hardcoded to the repository root:

https://github.com/helm/chart-releaser/blob/a5166bb02a405f244649abdb841e3d6c93ef99ae/pkg/releaser/releaser.go#L114

It is possible that the file is served from a path, for example:

```
https://org.github.io/repo/helm/charts/
```

I propose to add an option to the `index` command to make the `pages-index-path` configurable

**Comment by cpanato** [comment]
sounds good to me

**Comment by cscetbon** [comment]
Why not just respect index-path ? I set index-path to `website/helm/index.yaml` thinking it would be pushed to that location as well but got the behavior you describe which doesn't make sense to me.

**Comment by caleblloyd** [comment]
This was confusing to me as well, but upon looking into the source code It looks like `index-path` is the current working index file on the current branch. It doesn't even have to point to an existing file; the most up-to-date index file can be downloaded by passing the `--charts-repo` option to `cr index`

Since GitHub pages branches are often orphan branches with different directory structures, the `index-path` and `pages-index-path` could be different.

To make the `index-path` option work, operations on it should be performed on the `pages-branch` and not the current branch. I could work up a PR for this if that is the preferred behavior

**Comment by cscetbon** [comment]
Yeah it makes sense. A PR would be much appreciated I think and shouldn't be too hard. Lmk if you need help

**Comment by cscetbon** [comment]
@cpanato when can we expect a new release in order to use that new feature with [chart-releaser-action](https://github.com/helm/chart-releaser-action) ?

**Comment by cpanato** [comment]
> @cpanato when can we expect a new release in order to use that new feature with [chart-releaser-action](https://github.com/helm/chart-releaser-action) ?

i will work in some updates and will release soon, lets aim for next week
