### ISSUE TITLE
Semver precedence is broken

### ISSUE THREAD

**Issue by scottrigby** [helm/chart-releaser#16]
When I suggested using [semver spec Item 10 (metadata)](https://semver.org/#spec-item-10) for the chart name so we could still be semver compliant, I somehow missed this important point:
> Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

In our case, if there are two charts in a GitHub repo named `foo` and `bar` with the same version `1.0.0`, the tags `1.0.0+foo` and `1.0.0+bar` would have the same precedence 🤦‍♂️ @mattfarina confirmed this is how Helm handles build metadata. So… we can't do that.

I think we should go with what @prydonius suggested: `CHARTNAME-VERSION`. This way it's not valid semver (git release tags don't need to be for this), and so bypasses it altogether. This is also the same pattern `helm package` uses (minus the `.tgz`).

**Comment by scottrigby** [comment]
Note we can't revert #2, we just need to change the release name pattern.

**Comment by unguiculus** [comment]
Ah, didn't think of that. Makes sense.
