### ISSUE TITLE
Is allowed to have other files in the releases created by chart-releaser?

### ISSUE THREAD

**Issue by jvanz** [helm/chart-releaser#233]
This [repository](https://github.com/kubewarden/helm-charts/actions/runs/3463942212) uses the chart-releaser to do the job of releasing all the 3 helm charts. After the release is created some additional files are added to the release. This is causing issues. In the next time that new changes are pushed to the repository, chart-releaser fails because it trys to open the additional files as Helm charts. This is makes the CI job to failed.

Is it fine to add more assets in the releases created by chart-releaser? If so, how can I tell the tool to ignore the files that are not charts? 

If this is not supported, what do you think to add this feature? (I'm willing to work on that)

**Comment by mattfarina** [comment]
I think this is a bug in the way the index files are updated. Take a look at ....

https://github.com/helm/chart-releaser/blob/0eb1d31b98fd5b5aa73180644b89e1e959b2fb18/pkg/releaser/releaser.go#L171

In this code it assumes all files on the release are charts and does not check if they have a valid name or extension. I would suggest checking for that would be a valid fix.

**Comment by scottrigby** [comment]
I think you’re right Matt. Adding addtl files during CI to .cr-release-packages dir seems like a feature not a bug. We should't assume all assets on the release are charts 👌

**Comment by jvanz** [comment]
Cool, I'll work on this issue and open a PR with a fix for your review. :)
