### ISSUE TITLE
Publish on homebrew?

### ISSUE THREAD

**Issue by aegershman** [helm/chart-releaser#35]
In order to make `cr` easier to aquire and upgrade chart-releaser (without having to manually go to the github releases page, download it, move it to `bin/`, etc.), could this binary be made available on homebrew tap?

---

If you didn't want to submit it to the "main" homebrew tap or kubernetes tap, another option would be to update `.goreleaser` to publish a `cr.rb` file in the root of this project as part of the release process, and then users could do:

```
brew tap helm/chart-releaser https://github.com/helm/chart-releaser
brew install helm/chart-releaser/chart-releaser
```

[That is a technique it appears other CLI tools are taking](https://github.com/pivotal-cf/om/blob/master/.goreleaser.yml#L25-L38), though to be honest I can't speak to whether or not it's the best idea / if there are consequences of doing it that way

**Comment by unguiculus** [comment]
Fixed in #61
