### ISSUE TITLE
fatal: invalid reference: origin/gh-pages; exit status 128

### ISSUE THREAD

**Issue by Kerwood** [helm/chart-releaser#430]
When running the chart releaser action I get the following error.
```
...
Releasing charts...
Updating charts repo index...
cr index -o Kerwood -r helm-charts --push   # <---- Added this "echo" line to see what arguments was used.
Loading index file from git repository .cr-index/index.yaml
fatal: invalid reference: origin/gh-pages
Error: exit status 128
```

I'm not sure what the `fatal: invalid reference: origin/gh-pages` means but the branch do exist.
```
$ git branch -r
  origin/HEAD -> origin/main
  origin/gh-pages
  origin/main
```

Using `v1.6.1` of `cr`.

**Comment by Kerwood** [comment]
I see that the error is caused by my self.. 
I am trying to make a centralized helm-chart repo by adding my other application repos as submodules.
I forked the `chart-releaser-action` repo and did a little modification to the `lookup_changed_charts()` function to find all chart folders in the submodules. See changes here https://github.com/Kerwood/chart-releaser-action/commit/89ebe16f1017a9163016e6db184b5cbf3c04e108

I can replicate the error by
- Cloning my own repo and `cd` into it.
- Running `git submodule update --init --remote --merge` to download the submodule repos containing the charts.
- `mkdir test`
- `cd` into the submodule folder.
- Running `git worktree add --detach ../../test origin/gh-pages`

Above produces `fatal: invalid reference: origin/gh-pages`.

I understand that the issue is not a bug on the `cr` cli. But any suggestions would be appreciated.

**Comment by Kerwood** [comment]
The `chart-releaser-action` seems a bit complex and supports a lot use cases I dont need. I think I will create my own simple chart releaser action that supports my need of submodule/subfolder charts.

**Comment by larryli2** [comment]
Just a note anyone seeing the same error (but actually not related):
If you are using v1.7.0 and you see this error, this could be related to a bug, it is fixed in this PR: https://github.com/helm/chart-releaser/pull/486

**Comment by Kerwood** [comment]
If any one is interested in an alternative action, have a look at this one. https://github.com/Kerwood/chart-releaser-action
