### ISSUE TITLE
Support for multiple charts in single repo

### ISSUE THREAD

**Issue by deiga** [helm/chart-releaser#54]
Reading the code and documentation I couldn't figure out how to use this for a repo with multiple charts in it. Does it even support such use cases?

**Comment by cgiraldo** [comment]
Take a look to [chart-relaser github action](https://github.com/helm/chart-releaser-action/blob/master/cr.sh). It leverages chart-releaser binary and we use it to serve a repo with multiple charts through github pages.

**Comment by unguiculus** [comment]
It's specifically designed to support this use case.

**Comment by scottrigby** [comment]
@deiga I believe this has been answered. Please create a new issue or reach out on slack if you need further support on this. Thanks 😄
