### ISSUE TITLE
"unsupported protocol scheme " error when generating index.yaml

### ISSUE THREAD

**Issue by koustubhg** [helm/chart-releaser#55]
**version**: v0.2.3
**helm version 2**

I have configured the following  in my config file `chart-releaser.yaml`

```
owner: SouthbankSoftware
git-repo: provendb-helm
package-path: ./
git-base-url: https://api.github.com/
git-upload-url: https://uploads.github.com/
token: 2332
charts-repo: provendb-helm
index-path: ./index.yaml
```

I could upload the helm chart correctly with

`cr upload --config chart-releaser.yaml`

When I create an index like this
`cr index --config ./chart-releaser.yaml`

I get the following error:

`Error: Get provendb-helm/index.yaml: unsupported protocol scheme ""`

Am I missing something?

**Comment by unguiculus** [comment]
`charts-repo` must be a valid URL to your charts repo.
