### ISSUE TITLE
No release for Helm v3 merge

### ISSUE THREAD

**Issue by smark88** [helm/chart-releaser#56]
https://github.com/helm/chart-releaser/pull/47

This merge never had an official release cut?  Was this expected?

**Comment by Hermsi1337** [comment]
I would also love to see support for `Helmv3`. Looking forward to an updated release of this action (=

**Comment by spkane** [comment]
There is no release that includes these either from what I can tell:

```
  -b, --git-base-url string   GitHub Base URL (only needed for private GitHub)
  -u, --git-upload-url string GitHub Upload URL (only needed for private GitHub)
```

**Comment by unguiculus** [comment]
A new release with Helm 3 support was just cut.

**Comment by scottrigby** [comment]
https://github.com/helm/chart-releaser/releases/tag/v1.0.0-beta.1
