### ISSUE TITLE
Asset upload fails in a silent way when `git-upload-url` is incorrect.

### ISSUE THREAD

**Issue by spkane** [helm/chart-releaser#57]
For Github Enterprise, `chart-releaser` users need `git-base-url` and `git-upload-url` correctly, but the correct values are not always obvious.

Often they are along these lines:

```
https://example.com/api/v3/
https://example.com/api/uploads/
```

If however you set the upload URL incorrectly, let's say to something like `https://example.com/uploads/`, then `cr upload` will appear to work, but there will only be the 2 source code assets and the third asset is missing. This will become apparent when you run `cr index` and it always claims that nothing has changed, because it can't find any assets for the release.

The initial issue might be a problem in the `go-github` `Do` call, but basically if the asset upload fails the release should be rolled back (deleted) and a an appropriate log message should be displayed.

It is likely that the `cr index` command should also generate at least a warning when a release has no assets attached to it.

**Note:**
If you are trying to figure out what your upload_url is try to use a curl command like this:
`curl  -u username:token https://example.com/api/v3/repos/org/repo/releases`
and then look for `"upload_url"` - You need the part before `repos/`

**Comment by unguiculus** [comment]
Thanks for reporting this. Would you mind creating a PR that adds a section to the readme?

**Comment by spkane** [comment]
Added a note to the README in the above PR. This should help folks until a proper fix can be put into place.

**Comment by spkane** [comment]
@unguiculus Is there anything else that needs to happen to merge the related documentation update PR?

**Comment by unguiculus** [comment]
Merged. Thanks.
