### ISSUE TITLE
setup for using "cr index"...?

### ISSUE THREAD

**Issue by tony-kerz** [helm/chart-releaser#63]
likely operator error, but i'm having an issue setting up `index.yaml`.

i'm trying to run via docker image with something like:

```
docker run \
  --rm \
  -v /Users/tony/git-alt/helm-charts/build:/build \
  -e CR_OWNER=the-watchmen \
  -e CR_GIT_REPO=helm-charts \
  -e CR_PACKAGE_PATH=/build \
  -e CR_INDEX_PATH=/build/index.yaml \
  -e CR_CHARTS_REPO=https://github.com/the-watchmen/helm-charts \
  -e CR_TOKEN={my-token} \
  quay.io/helmpack/chart-releaser:v0.2.3 \
  cr index
```

and seeing:

```
====> UpdateIndexFile new index at /build/index.yaml
Error: GET https://api.github.com/repos/the-watchmen/helm-charts/releases/tags/index: 404 Not Found []
```

contents of `/Users/tony/git-alt/helm-charts/build`:
```
bash-3.2$ ls -la build
total 32
drwxr-xr-x  5 tony  staff   160 Mar 22 13:29 .
drwxr-xr-x  9 tony  staff   288 Mar 22 13:29 ..
-rw-r--r--  1 tony  staff   528 Mar 22 13:29 index.yaml
-rw-r--r--  1 tony  staff  1477 Mar 22 13:29 micro-service-1.0.0.tgz
-rw-r--r--  1 tony  staff  5542 Mar 22 13:29 tls-1.0.0.tgz
```

am i missing some pre-requisite steps? 

i manually created a `gh-pages` branch, but that didn't help.

[here is the repo](https://github.com/the-watchmen/helm-charts) that i am working with...

**Comment by unguiculus** [comment]
You configured https://github.com/the-watchmen/helm-charts as you charts repo. You must specify the Helm charts repo that serves your `index.yaml` instead, not the Git repo.

**Comment by tony-kerz** [comment]
thanks for the tip @unguiculus!

in my case, i'm using github-pages to serve my index.yaml, so my "helm chart repo" is `https://the-watchmen.github.io/helm-charts`...

but i'm serving `index.yaml` from the `master` branch `docs` folder, so updating that would require a commit to that branch...

seems like i'm not understanding the functionality of `cr index`...

is it designed to work with something more like [chartmuseum](https://chartmuseum.com/)?

```
⋊> ~/g/helm-charts on master ⨯ docker run \                                              10:38:10
                                 --rm \
                                 -v /Users/tony/git-alt/helm-charts/build:/build \
                                 -e CR_OWNER=the-watchmen \
                                 -e CR_GIT_REPO=helm-charts \
                                 -e CR_PACKAGE_PATH=./build \
                                 -e CR_INDEX_PATH=./build/index.yaml \
                                 -e CR_CHARTS_REPO=https://the-watchmen.github.io/helm-charts \
                                 -e CR_TOKEN=$CR_TOKEN \
                                 quay.io/helmpack/chart-releaser:v1.0.0-beta.1 \
                                 cr index
====> Using existing index at ./build/index.yaml
Error: GET https://api.github.com/repos/the-watchmen/helm-charts/releases/tags/index: 404 Not Found []
```

**Comment by tony-kerz** [comment]
doh! ok, i think i get it now.

i originally thought that i was creating `index.yaml` and that `cr index` was publishing it,
but now i'm getting that `cr index` is just creating `index.yaml` locally, and it us up to me to publish it somewhere.

related question, why does `cr index` need `--package-path`, isn't it using the releases of the git repo to figure out what to put in `index.yaml`? what is it doing with the package-path folder in this case?
