### ISSUE TITLE
Feature: Simple HTML overview next to index.yaml

### ISSUE THREAD

**Issue by WyriHaximus** [helm/chart-releaser#66]
Having the `index.yaml` generated is great and all, but have you considered adding (or accepting a PR That adds) an `index.html` that shows a simple list of all the charts and the latest version? So that who ever visits the chart repo URL we pass around have an idea of what's in the repo without having to parse the `YAML`?

**Comment by adibrastegarnia** [comment]
+1

**Comment by SeanCondon** [comment]
Please feel free to use 
https://github.com/onosproject/onos-helm-charts/blob/master/build/cmd/index2md/index2md.go

It generates Markdown from the `index.yaml`.

**Comment by WyriHaximus** [comment]
Cool will have a look 👍

**Comment by unguiculus** [comment]
@SeanCondon Thanks for mentioning your solution. I like the idea but would say this is out of scope for chart-releaser.

**Comment by sneumann** [comment]
Hi, I'd also love to have a rendering of the index.yaml so my charts are hosted not only machine readable, but also shows humans visiting those gh-pages what to find. If some JavaScript hackers are around, they could write an index.html where JS reads the index.yaml and renders tables from the chart entries. Then, no change to cr would be needed. Yours, Steffen
