### ISSUE TITLE
Index failing because apparently GitHub API does not allow listing tags

### ISSUE THREAD

**Issue by moxious** [helm/chart-releaser#69]
This URL: https://api.github.com/repos/neo4j-contrib/neo4j-helm/releases/tags/ is a 404.

This URL: (a specific release) https://api.github.com/repos/neo4j-contrib/neo4j-helm/releases/tags/4.0.4-2 works just fine.

Is it built into the tool, the assumption that the GitHub API will allow you to enumerate releases with this endpoint?  Because GitHub appears not to allow that.

```
$ cr index -c https://github.com/neo4j-contrib/neo4j-helm.git -r neo4j-helm -i index.yaml -o neo4j-contrib -p . 
====> UpdateIndexFile new index at index.yaml
Error: GET https://api.github.com/repos/neo4j-contrib/neo4j-helm/releases/tags/: 404 Not Found []
Usage:
  cr index [flags]

Flags:
  -c, --charts-repo string      The URL to the charts repository
  -b, --git-base-url string     GitHub Base URL (only needed for private GitHub) (default "https://api.github.com/")
  -r, --git-repo string         GitHub repository
  -u, --git-upload-url string   GitHub Upload URL (only needed for private GitHub) (default "https://uploads.github.com/")
  -h, --help                    help for index
  -i, --index-path string       Path to index file (default ".cr-index/index.yaml")
  -o, --owner string            GitHub username or organization
  -p, --package-path string     Path to directory with chart packages (default ".cr-release-packages")
  -t, --token string            GitHub Auth Token (only needed for private repos)

Global Flags:
      --config string   Config file (default is $HOME/.cr.yaml)
```

**Comment by ms32035** [comment]
Ran into the same issue and I'm still not sure if this is a bug or me doing something wrong.

**Comment by ms32035** [comment]
Ok, looks like I made some progress. It seems that the index command iterates over all files in the directory, so if there is something that isn't a helm chart it will fail. Other possibility might be due to folders starting with a dot are causing this. Anyways, an index of a directory with tgz files only was generated correctly

**Comment by oasisvali** [comment]
I see this issue intermittently as well (using chart-releaser-action). It seems like an issue with the github API that causes the listing of tags to fail. Re-running the releaser job works so it seems like some kind of race-condition on the github side. The specific error for me was:

```
Error: GET https://api.github.com/repos/conscia/charts/releases/tags/xyz-1.0.0
```

Even though the tag being requested, had just been created by the previous step

**Comment by unguiculus** [comment]
I've seen this issue as well. It indeed looks like a race condition with GitHub. We should add some kind of retry logic.

**Comment by invidian** [comment]
I was trying out set of actions for creating charts repository and it seems I'm still hitting this issue: https://github.com/invidian/helm-charts/runs/2271591951?check_suite_focus=true. Moreover, retrying the release action doesn't seem to help, as then it does nothing and GitHub Pages does not get updated. At this point, I'm not able to start using the whole stack, as I'm stuck with releasing initial chart version.

**Comment by invidian** [comment]
Hmm, eventually after 5th attempt with removing release, deleting tag and re-pushing to master it eventually converged, yay.
