### ISSUE TITLE
cr upload pushes to incorrect commit point

### ISSUE THREAD

**Issue by darkn3rd** [helm/chart-releaser#70]
When you create a release at an earlier commit point, `cr upload` release a package at the current commit point in `origin/master`.  

### STEPS

As an example, I have `ef6f90` that you want to be `dgraph-0.0.6`, and I want to publish an earlier commit at `c4a062de` that you want to be `dgraph-0.0.5`

```
* ef6ef90 - (HEAD -> master, origin/master, origin/HEAD) super duper tls secret support (#37) (2 days ago) <me>
* 5debc54 - some bug that was fixed (6 days ago) <another dev>
* c4a062e - ingress on steroids support (4 weeks ago) <me>
```

Then you do:

```
git checkout c4a062e
helm package charts/dgraph --destination .packages/
cr upload --config ~/.config/chart-releaser/config.yaml
```

### Actual Results

It creates a tag at `ef6ef90`, not `c4a062e`.

### Expected Results

I wanted the tag at `c4a062e` or have a command option or other method to do that.

**Comment by unguiculus** [comment]
chart-releaser has an option to specify the target commit. That should help you achieve what you want.

See https://github.com/helm/chart-releaser/blob/master/cr/cmd/upload.go#L52
