### ISSUE TITLE
Optional tag postfix

### ISSUE THREAD

**Issue by stevehipwell** [helm/chart-releaser#71]
When using the _chart-releaser_ via the official _GitHub chart-releaser Action_ on a repo containing the application as well as the _Helm_ chart the tags that are created are confusing unless something is added to the chart name to clarify that it is a chart (see https://github.com/kubernetes-sigs/descheduler/issues/248#issuecomment-663201319 & https://github.com/kubernetes/autoscaler/pull/3393).

This results in the two charts above being called `descheduler/descheduler-chart` & `autoscaler/cluster-autoscaler-chart` respectively just to make sure the tags are created correctly.

It would be really useful to enable a custom tag prefix via the `cr` command so these charts can loose the `-chart` postfix from their name which is confusing and unnecessary beyond tagging concerns.

**Comment by damemi** [comment]
+1, because the Chart releases are located in the same repo as the project itself, it's confusing that not only the tags would have the same name but also the release. Being able to set a tag/release name pattern would be great
