### ISSUE TITLE
How to generate index.yaml file?

### ISSUE THREAD

**Issue by santosh-hegde** [helm/chart-releaser#80]
Should I use `cr index` to generate index.yaml file?
I ran 
`cr index -i ./index.yaml -p .deploy -o <MyID> -r charts -c https://github.xyz.com/MyID/charts/releases/download --token <myToken> `
This returns 
```
====> Using existing index at ./index.yaml
Error: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
Usage:
  cr index [flags]
```
And index.yaml file contains
` <h3>You are being redirected to your identity provider in order to authenticate.</h3>`

But the same token works with `cr upload`. So its not an issue token issue.

**Comment by lukaszmitka-aptiv** [comment]
You may need to provide correct url to charts repository
e.g. `-c, --charts-repo` this should point to gh-pages <owner>.github.io/<repo> ...

**Comment by unguiculus** [comment]
As @lukasz-mitka mentioned, the URL must point to the charts repo.
