### ISSUE TITLE
Update generated timestamp in index.yaml

### ISSUE THREAD

**Issue by onedr0p** [helm/chart-releaser#90]
Hello

Sorry if this is more of a question than a bug. We're using the chart-releaser over at https://github.com/k8s-at-home/charts

We've noticed that the top level `generated` field in the `index.yaml` is not being updated when charts are being updated. Tools like [flux2](https://github.com/fluxcd/flux2) expect this field to be updated when a chart is released so it knows when to update the repo.

You can see in [index.yaml](https://github.com/k8s-at-home/charts/blob/gh-pages/index.yaml) the `generated` field is not being updated and it's currently pinned to `generated: "2019-12-22T07:05:20.914237208Z"`

My question is should this field be updated when a new chart is released, or is it something that could be supported in the future?

Thanks!

**Comment by Niksko** [comment]
FYI this is now fixed upstream in Flux v2 release 0.7.2, via source-controller 0.7.1 via https://github.com/fluxcd/source-controller/pull/267.
