### ISSUE TITLE
CR index push does not work for Github Enterprise Users

### ISSUE THREAD

**Issue by romainx** [helm/chart-releaser#96]
Hello,

I've noticed that `cr index --push` does not work for Github Enterprise Users because it tries to use `github.com` to push index file. The reason is that the base URL is hardcoded:

https://github.com/helm/chart-releaser/blob/c7da1f33e548569eb543c56a3e913f1c712fe661/pkg/releaser/releaser.go#L210

However, I dot not know if there is a straightforward way to fix it since `git-base-url` is used to configure the GitHub API URL (`https://ghe.example.com/api/v3/`) and not the GitHub base URL (`https://ghe.example.com/`).

I could draft a PR, but I think I would need some advice on how best to fix this.

I guess we could / should have something like that:

| property         | Current                    | GitHub.com                 | GitHub Ent.                         |
|------------------|----------------------------|----------------------------|-------------------------------------|
| `git-base-url`   | https://api.github.com     | https://github.com         | https://ghe.example.com             |
| `git-upload-url` | https://uploads.github.com | https://uploads.github.com | https://ghe.example.com/api/uploads |
| `git-api-url`    | NA                         | https://api.github.com     | https://ghe.example.com/api/v3      |

Best

**Comment by gimler** [comment]
seems duplicate of #91

**Comment by romainx** [comment]
@gimler you're right my bad. So I'm closing it in favor of #91.
